// <auto-generated />
namespace SimpleSite.Migrations.Identity
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class CssTheme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CssTheme));
        
        string IMigrationMetadata.Id
        {
            get { return "201503301506018_CssTheme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
