//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filament.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Project_Rate = new HashSet<Project_Rate>();
        }
    
        public int ProjectId { get; set; }
        public string Project_Title { get; set; }
        public string Project_Manager { get; set; }
        public string Project_Type { get; set; }
        public string Billing_Type { get; set; }
        public string Start_Date { get; set; }
        public bool Active { get; set; }
        public Nullable<int> ClientId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Project_Rate> Project_Rate { get; set; }
    }
}
